#The below settings common for all services

#Registering service into EurekaServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka #Enable for standalone
      #defaultZone: http://eureka-peer1:8001/eureka,http://eureka-peer2:8002/eureka #Enable for cluster
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

#To enable all endpoints to admin-server    
management:
  endpoints:
    web:
      exposure:
        include: '*'
