#The below settings common for all services

#Registering service into EurekaServer
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8888/eureka/ #Enable for standalone
      defaultZone: http://localhost:8001/eureka/, http://localhost:8002/eureka/ #Enable for cluster

#To enable all endpoints to admin-server    
management:
  endpoints:
    web:
      exposure:
        include: '*'
